"""
Django settings for members project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l_+ya#^z)@&o^%k*z$)-z!=dh$es_9i!w!+=z8-wg4nub@e!#g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'membersapp.app.apps.AppAppConfig',
    'membersapp.account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTHENTICATION_BACKENDS = (
    # 'membersapp.auth.AuthBackend',
    'membersapp.account.util.auth.AuthBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'membersapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'membersapp.context_processor.settings_auth'
            ],
        },
    },
]

WSGI_APPLICATION = 'membersapp.wsgi.application'

# Adding Crypt to default hashers to allow import from previous members app
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.ScryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'membersdjango',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATE_FORMAT = "Y-m-d"
DATETIME_INPUT_FORMATS = ['%Y-%m-%d']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# account
ACCOUNTS_NOREPLY_FROM = "pgweb@localhost"                # Address to send account messages from
NOTIFICATION_EMAIL = "pgweb@localhost"                   # Address to send notifications *to*
NOTIFICATION_FROM = "pgweb@localhost"                    # Address to send notifications *from*
# Configure recaptcha. Most details contain keys and are thus handled
# in settings_local.py. Override NOCAPTCHA to actually use them.
NOCAPTCHA = True
RECAPTCHA_SITE_KEY = ""
RECAPTCHA_SECRET_KEY = ""
SITE_ROOT = "http://localhost:8000"
# Notification emails when a members sends a new contributing application
# or updates an existing one
SEND_NOTIFICATION_EMAILS = True
NOTIFICATION_EMAILS_DESTINATION = "membership@spi-inc.org"

# Override in local settings
USE_PG_COMMUNITY_AUTH = False  # Right now we *always* do, but this is used to turn on/off some local features
PGAUTH_REDIRECT = "http://localhost:8000/account/auth/1/"
PGAUTH_KEY = "encryption_key"
PGAUTH_REDIRECT_SUCCESS = "http://localhost:8000"
PGAUTH_SIGNUP = "http://localhost:8000/account/signup/"
PGAUTH_ROOT = "http://localhost:8000"
PGAUTH_CHANGEPASSWD = "http://localhost/account/changepwd"
LOGIN_URL = "/account/login/"
LOGIN_REDIRECT_URL = '/'
LOGOUT_URL = '/account/logout/'

PGLISTER_URL = 'https://pglister.spi-inc.org'
REIMBURSEMENTS_URL = 'https://reimbursements.spi-inc.org'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = os.path.join(BASE_DIR, "./media/")

EMAIL_HOST = 'localhost'
EMAIL_PORT = '25'

# IPs that will get access to the -private subs list
LIST_HOSTS = ['127.0.0.1', '::1']

try:
    from .local_settings import *
except ImportError:
    pass

if USE_PG_COMMUNITY_AUTH:
    SIGNUP_URL = PGAUTH_SIGNUP
    CHANGEPASSWD_URL = PGAUTH_CHANGEPASSWD
    RESETPASSWD_URL = PGAUTH_CHANGEPASSWD
    ACCOUNT_URL = PGAUTH_ROOT
else:
    SIGNUP_URL = '/account/signup'
    CHANGEPASSWD_URL = '/account/changepwd'
    RESETPASSWD_URL = '/account/reset'
    ACCOUNT_URL = '/'
