# Generated by Django 3.2 on 2022-05-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220513_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='ismember',
        ),
    ]
