# Generated by Django 3.2 on 2022-06-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_members_ismember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='manager',
            field=models.ForeignKey(db_column='manager', limit_choices_to={'ismanager': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='app2manager', to='app.members'),
        ),
    ]
