# Generated by Django 3.2 on 2022-06-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_applications_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='appdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='approve_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='emailkey_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='lastchange',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager', limit_choices_to={'ismanager': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='app2manager', to='app.members'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='manager_date',
            field=models.DateField(null=True, verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='validemail_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='expirydate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='firstdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='lastactive',
            field=models.DateField(null=True),
        ),
    ]
