# Generated by Django 3.2 on 2022-07-01 13:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220626_1415'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voteelection',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='period_stop',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='system',
            field=models.IntegerField(verbose_name='Voting system'),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Vote title'),
        ),
    ]
