# Generated by Django 3.2 on 2022-07-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220701_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteelection',
            name='period_start',
            field=models.DateTimeField(null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='period_stop',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
    ]
