# Generated by Django 3.2 on 2022-10-17 07:58

import django.core.validators
from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220706_1832'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voteoption',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='votevote',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='period_start',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='period_stop',
            field=models.DateTimeField(null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='End date'),
        ),
    ]
