# Generated by Django 3.2 on 2022-10-20 20:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20221017_0758'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applications',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='applications',
            name='emailkey',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='emailkey_date',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='validemail',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='validemail_date',
        ),
    ]
