# Generated by Django 3.2 on 2022-10-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221020_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='firstdate',
        ),
    ]
