# Generated by Django 3.2 on 2022-10-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_members_firstdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='members',
            name='pgpkey',
        ),
        migrations.RemoveField(
            model_name='members',
            name='phone',
        ),
    ]
