# Generated by Django 3.2 on 2023-02-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20221027_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='ismember',
            field=models.BooleanField(default=False),
        ),
    ]
