# Generated by Django 5.1 on 2025-03-20 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_auto_20230216_1931"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="comment",
            field=models.TextField(null=True, verbose_name="Manager Comments"),
        ),
        migrations.AlterField(
            model_name="applications",
            name="member",
            field=models.ForeignKey(
                db_column="member",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="app2member",
                to="app.members",
            ),
        ),
        migrations.AlterField(
            model_name="members",
            name="memid",
            field=models.OneToOneField(
                db_column="memid",
                on_delete=django.db.models.deletion.RESTRICT,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
