# Generated by Django 4.2 on 2025-06-19 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_add_ballots_to_elections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteballot",
            name="winners",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
