# Generated by Django 4.2 on 2025-06-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_voteballot_winners"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="applications",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="members",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="voteelection",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="voteoption",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="votevote",
            managers=[],
        ),
    ]
