# Generated by Django 4.2 on 2025-08-12 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_applications_managers_alter_members_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteballot",
            name="quorum",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
