# Generated by Django 4.2 on 2025-08-12 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_voteballot_quorum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteballot",
            name="quorum",
            field=models.FloatField(
                default=0.35,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
