# Generated by Django 4.2 on 2025-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_voteballot_quorum"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteelection",
            name="nb_contrib",
            field=models.IntegerField(
                null=True,
                verbose_name="Number of contributing members on vote start (for quorum calculation)",
            ),
        ),
    ]
