# Generated by Django 5.2 on 2026-06-15 10:54

import django.db.models.deletion
import membersapp.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_voteelection_public_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteUniqueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_link",
                    models.CharField(
                        default=membersapp.app.models.generate_token, max_length=64
                    ),
                ),
                (
                    "vote_ref",
                    models.ForeignKey(
                        db_column="vote_ref",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.voteelection",
                    ),
                ),
                (
                    "voter_ref",
                    models.ForeignKey(
                        db_column="voter_ref",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.members",
                    ),
                ),
            ],
        ),
    ]
