# Generated by Django 3.2 on 2022-02-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('memid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('pgpkey', models.CharField(max_length=50)),
                ('firstdate', models.DateTimeField()),
                ('expirydate', models.DateTimeField()),
                ('ismember', models.BooleanField(default=False)),
                ('iscontrib', models.BooleanField(default=False)),
                ('ismanager', models.BooleanField(default=False)),
                ('sub_private', models.BooleanField(default=False)),
                ('lastactive', models.DateTimeField()),
                ('createvote', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='VoteElection',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('period_start', models.DateTimeField(auto_now_add=True)),
                ('period_stop', models.DateTimeField()),
                ('winners', models.IntegerField(default=1)),
                ('system', models.IntegerField()),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.RESTRICT, to='app.members')),
            ],
            options={
                'db_table': 'vote_election',
            },
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('sort', models.IntegerField()),
                ('option_character', models.CharField(max_length=1)),
                ('election_ref', models.ForeignKey(db_column='election_ref', on_delete=django.db.models.deletion.RESTRICT, to='app.voteelection')),
            ],
            options={
                'db_table': 'vote_option',
                'unique_together': {('election_ref', 'option_character'), ('election_ref', 'sort')},
            },
        ),
        migrations.CreateModel(
            name='VoteVote',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('private_secret', models.CharField(max_length=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('send_notify', models.BooleanField(default=False)),
                ('election_ref', models.ForeignKey(db_column='election_ref', on_delete=django.db.models.deletion.RESTRICT, to='app.voteelection')),
                ('voter_ref', models.ForeignKey(db_column='voter_ref', on_delete=django.db.models.deletion.RESTRICT, to='app.members')),
            ],
            options={
                'db_table': 'vote_vote',
                'unique_together': {('voter_ref', 'election_ref')},
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False)),
                ('appdate', models.DateTimeField()),
                ('emailkey', models.CharField(max_length=50)),
                ('emailkey_date', models.DateTimeField()),
                ('validemail', models.BooleanField()),
                ('validemail_date', models.DateTimeField()),
                ('contrib', models.TextField()),
                ('comment', models.TextField()),
                ('lastchange', models.DateTimeField()),
                ('manager_date', models.DateTimeField()),
                ('approve', models.BooleanField()),
                ('approve_date', models.DateTimeField()),
                ('contribapp', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(db_column='manager', on_delete=django.db.models.deletion.RESTRICT, related_name='app2manager', to='app.members')),
                ('member', models.ForeignKey(db_column='member', on_delete=django.db.models.deletion.RESTRICT, related_name='app2member', to='app.members')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='VoteVoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField()),
                ('option_ref', models.ForeignKey(db_column='option_ref', on_delete=django.db.models.deletion.RESTRICT, to='app.voteoption')),
                ('vote_ref', models.ForeignKey(db_column='vote_ref', on_delete=django.db.models.deletion.RESTRICT, to='app.votevote')),
            ],
            options={
                'db_table': 'vote_voteoption',
                'unique_together': {('vote_ref', 'option_ref')},
            },
        ),
    ]
