# Generated by Django 3.2 on 2022-02-20 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_members_memid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votevote',
            old_name='send_notify',
            new_name='sent_notify',
        ),
        migrations.RemoveField(
            model_name='votevote',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='votevote',
            name='late_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='appdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='approve',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='approve_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='contrib',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='contribapp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='emailkey',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='emailkey_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='lastchange',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='manager',
            field=models.ForeignKey(db_column='manager', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='app2manager', to='app.members'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='manager_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='member',
            field=models.ForeignKey(db_column='member', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app2member', to='app.members'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='validemail',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='validemail_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='expirydate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='firstdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='lastactive',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='memid',
            field=models.OneToOneField(db_column='memid', db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='members',
            name='pgpkey',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='sub_private',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='period_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='voteelection',
            name='period_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voteoption',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='votevote',
            name='private_secret',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='votevote',
            name='voter_ref',
            field=models.ForeignKey(db_column='voter_ref', null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.members'),
        ),
        migrations.AlterField(
            model_name='votevoteoption',
            name='preference',
            field=models.IntegerField(null=True),
        ),
    ]
